# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: required

install:
  - Rscript -e 'options(repos = c(CRAN = "http://cran.rstudio.com")); install.packages("MODIS", repos= "http://r-forge.r-project.org")'


r_binary_packages:
  - rgdal

bioc_packages:
  - rhdf5

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change
