# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: required

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gdal-bin libgdal1 libgdal1-dev libproj-dev libgdal1h libnetcdf-dev netcdf-bin


bioc_packages:
  - rhdf5

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change
